config/routes.rb
Rails.application.routes.draw do
  resources :users do
    get :toggle_status, on: :member
    get :remove, on: :member
  end

  root 'users#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # broadcasts
  after_create_commit {broadcast_prepend_to 'users'}
  after_update_commit {broadcast_replace_to 'users'}
  after_destroy_commit {broadcast_remove_to 'users'}
  VALID_STATUS = %w[active inactive].freeze
  VALID_EMAIL_FORMAT = URI::MailTo::EMAIL_REGEXP
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    format: { with: VALID_EMAIL_FORMAT }
  validates :phone, presence: true
  validates :name, presence: true
  validates :status, presence: true, inclusion: { in: VALID_STATUS }
  validates :title, presence: true
  scope :order_by_columns, lambda {
                             order(updated_at: :asc, name: :asc, email: :asc, title: :asc, phone: :asc, status: :asc)
                           }
  include PgSearch
  pg_search_scope :search, against: %i[email phone name status title]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[toggle_status show edit update remove]

  def index
    @user = User.new
    @users = if params[:query].present?
               User.search(params[:query]).page params[:page]
             else
               sorted_data
             end
    respond_to do |format|
      format.html
      format.json { head :no_content }
    end

  end

  def show; end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    value = @user.status == 'active' ? 'inactive' : 'active'
    respond_to do |format|
      if @user.update(status: value)
        format.html { redirect_to users_url, notice: "User was successfully made #{value.humanize}." }
        format.json { head :no_content }
      else
        format.html { render :index, status: :unprocessable_entity }
      end
    end
  end

  def remove
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully Removed.' }
      format.json { head :no_content }
    end
  end

  def search
    
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def sorted_data
    if params[:sort]
      User.order(params[:sort]).page params[:page]
    else
      User.page params[:page]
    end
  end

  def user_params
    params.fetch(:user).permit(:email, :title, :name, :phone, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_status(user)
    user.status == 'active' ? 'Deactivate' : 'Activate'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebspoonsTask</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="skins-air">
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with model: user do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :phone %>
    <%= form.telephone_field :phone, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :status %><br>
    <%= form.label :status, 'Active', value: 'active' %>
    <%= form.radio_button :status, 'active' %>
    <%= form.label :status, 'Inactive' %>
    <%= form.radio_button :status, 'inactive' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<%# <%= turbo_frame_tag dom_id(user) do %1> %>
  <tr id="<%= dom_id user %>" >
     <td><%= user.name %></td>
     <td><%= user.email %></td>
     <td><%= user.title %></td>
     <td><%= user.phone %></td>
     <td class=<%="#{user.status == 'active' ? 'green' : 'red'}"%>><%= user.status %></td>
     <td><%= link_to 'Show', user %></td>
     <td><%= link_to 'Edit', edit_user_path(user) %></td>
     <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
   </tr>
<%# <% end %1> %>

app/views/users/create_turbo_stream.erb
<%= turbo_stream.append 'users', @user %>

app/views/users/edit.html.erb
<h1>Editing User</h1>
<%= turbo_frame_tag "user" do %>
  <%= render 'form', user: @user %>
<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>
<% end %>

app/views/users/index.html.erb
<%= turbo_stream_from @users %>
<%= turbo_frame_tag "user" do %>

<%= form_tag users_path, method: :get do %>
  <p> Search for users </p>
  <%= text_field_tag :query, nil, placeholder: 'Enter search word' %>
  <%= submit_tag "Search", class: 'btn btn-sm btn-primary' %><span><%= link_to 'Reset', users_path, class: 'btn btn-sm btn-secondary' %></span>
<% end %>

<p id="notice"><%= notice %></p>
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th><%= link_to "Name", sort: "name"%> </th>
      <th><%= link_to "Email", sort: "email"%> </th>
      <th><%= link_to "Title", sort: "title"%> </th>
      <th><%= link_to "Phone", sort: "phone"%> </th>
      <th><%= link_to "Status", sort: "status"%> </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id='users'>
    <% @users.each do |user| %>
 <tr>
     <td><%= user.name %></td>
     <td><%= user.email %></td>
     <td><%= user.title %></td>
     <td><%= user.phone %></td>
     <td class=<%="#{user.status == 'active' ? 'green' : 'red'}"%>><%= user.status %></td>
     <td> <%= link_to 'View', user, class: 'btn btn-sm btn-info active' %></td>
     <td> <%= link_to 'Edit', edit_user_path(user), class: 'btn btn-sm btn-primary' %></td>
     <td> <%= link_to 'Remove', remove_user_path(user), method: :get, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %></td>
     <td><%= link_to user_status(user), toggle_status_user_path(user), data: { confirm: 'Are you sure?' } , class: "btn btn-sm #{user.status == 'active' ? 'btn-danger' : 'btn-info'} " %></td>
 </tr>
   <%end%>
  </tbody>
</table>

<b>
<%= paginate @users %>
<button onclick="document.getElementById('id01').style.display='block'" class="w3-button w3-black my-4">New User</button>
<% end %>
<div id="id01" class="w3-modal" style="display: none">
  <div class="w3-modal-content">
    <div class="w3-container">
           <h5 class="modal-title" id="exampleModalLabel">New User</h5>
      <div class="modal-body">
        <%# <%= turbo_frame_tag "user", src: new_user_path, target: '_top' %1> %>
        <%= turbo_frame_tag "user" do %>
          <%= render 'form', user: @user %>
        <% end %>
      </div>
      <div class="modal-footer">
       <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" onclick="document.getElementById('id01').style.display='none'">
        Close
       </button>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>New User</h1>
<%# <%= turbo_frame_tag "user" do %1> %>
<%# <%= render 'form', user: @user %1> %>

<%# <%= link_to 'Back', users_path %1> %>
<%# <% end %1> %>
<%# <%= turbo_frame_tag "user", target: 'top' do %>%>
<%#   <%= render 'form', user: @user %>%>
<%# <%end%>%>

<h1>New User</h1>
<%= turbo_frame_tag "user", target: 'top' do %>
  <%= render 'form', user: @user %>
  <%= link_to 'Back', users_path, "data-turbo-frames": "top" %>
<% end %>

app/views/users/show.html.erb
<%= turbo_frame_tag "user" do %>
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Title:</strong>
  <%= @user.title %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Status:</strong>
  <%= @user.status %>
</p>
<% end %>